# Generated by Django 4.1.4 on 2023-05-04 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_in', models.DateTimeField(auto_now_add=True, db_column='created_in', null=True, verbose_name='Fecha de creación')),
                ('modified_in', models.DateTimeField(auto_now=True, db_column='modified_in', null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.UUIDField(db_column='created_by', editable=False, null=True)),
                ('modified_by', models.UUIDField(db_column='modified_by', editable=False, null=True)),
                ('deleted_by', models.UUIDField(db_column='deleted_by', editable=False, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_in', models.DateTimeField(auto_now_add=True, db_column='created_in', null=True, verbose_name='Fecha de creación')),
                ('modified_in', models.DateTimeField(auto_now=True, db_column='modified_in', null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.UUIDField(db_column='created_by', editable=False, null=True)),
                ('modified_by', models.UUIDField(db_column='modified_by', editable=False, null=True)),
                ('deleted_by', models.UUIDField(db_column='deleted_by', editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_series', to='movies_series.type')),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='movies_watched', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Película o Serie',
                'verbose_name_plural': 'Películas y Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsersRating',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_in', models.DateTimeField(auto_now_add=True, db_column='created_in', null=True, verbose_name='Fecha de creación')),
                ('modified_in', models.DateTimeField(auto_now=True, db_column='modified_in', null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.UUIDField(db_column='created_by', editable=False, null=True)),
                ('modified_by', models.UUIDField(db_column='modified_by', editable=False, null=True)),
                ('deleted_by', models.UUIDField(db_column='deleted_by', editable=False, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies_series.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntuación de Usuario',
                'verbose_name_plural': 'Puntuaciones de Usuarios',
                'unique_together': {('movie', 'user')},
            },
        ),
    ]
