# Generated by Django 4.1.4 on 2023-05-03 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_in', models.DateTimeField(auto_now_add=True, db_column='created_in', null=True, verbose_name='Fecha de creación')),
                ('modified_in', models.DateTimeField(auto_now=True, db_column='modified_in', null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.UUIDField(db_column='created_by', editable=False, null=True)),
                ('modified_by', models.UUIDField(db_column='modified_by', editable=False, null=True)),
                ('deleted_by', models.UUIDField(db_column='deleted_by', editable=False, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_in', models.DateTimeField(auto_now_add=True, db_column='created_in', null=True, verbose_name='Fecha de creación')),
                ('modified_in', models.DateTimeField(auto_now=True, db_column='modified_in', null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.UUIDField(db_column='created_by', editable=False, null=True)),
                ('modified_by', models.UUIDField(db_column='modified_by', editable=False, null=True)),
                ('deleted_by', models.UUIDField(db_column='deleted_by', editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=100)),
                ('number_of_views', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('number_of_ratings', models.PositiveIntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_series.type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('watched', models.BooleanField(default=False)),
                ('movie_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_series.movieseries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie_series')},
            },
        ),
    ]
