# Generated by Django 4.1.4 on 2023-05-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movieseries',
            name='gender',
        ),
        migrations.AddField(
            model_name='movieseries',
            name='genre',
            field=models.ManyToManyField(to='movies_series.gender'),
        ),
    ]
