# Generated by Django 4.1.4 on 2023-05-03 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies_series', '0004_rename_genre_movieseries_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='created_by',
            field=models.UUIDField(db_column='created_by', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, db_column='created_in', null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deleted_by',
            field=models.UUIDField(db_column='deleted_by', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userrating',
            name='modified_by',
            field=models.UUIDField(db_column='modified_by', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='modified_in',
            field=models.DateTimeField(auto_now=True, db_column='modified_in', null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
